/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store_stream.proto

package org.apache.hugegraph.store.grpc.stream;

import java.nio.ByteBuffer;

public interface KvStreamOrBuilder extends
        // @@protoc_insertion_point(interface_extends:KvStream)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *query times.
   * </pre>
   *
   * <code>int32 seq_no = 1;</code>
   * @return The seqNo.
   */
  int getSeqNo();

  /**
   * <pre>
   *true=no more data
   * </pre>
   *
   * <code>bool over = 2;</code>
   * @return The over.
   */
  boolean getOver();

  /**
   * <code>uint32 version = 4;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>bytes stream = 5;</code>
   * @return The stream.
   */
  ByteBuffer getStream();
  /**
   * <code>.KvStreamType type = 6;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.KvStreamType type = 6;</code>
   * @return The type.
   */
  org.apache.hugegraph.store.grpc.stream.KvStreamType getType();
}
