name: Feature request (新需求 / 功能)
description: Give an idea for HugeGraph
title: '[Feature] describe the new feature'
labels:
  - feature

body:
  - type: textarea
    attributes:
      label: Feature Description (功能描述)
      description: |
        > 请简要描述新功能 / 需求的使用场景或上下文, 最好能给个具体的例子说明
      placeholder: type the feature description here 
    validations:
      required: true
