#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

net:
  kv:
    scanner:
      buffer.size: 10000
      page.size: 20000
      chan.size: 1

pd:
  address: 10.14.139.71:8686

scanner:
  #graph: 'default/icbc_hstoregraph/g'
  graph: 'DEFAULT/hugegraph/g'

  table: 'g+ie'
  #table: 'g+v'
  max: 10_000_000
  mod: 1_000_000

committer:
  graph: 'STORE_CLI'
  table: 'benchmark'
  amount: 1_000_000
