name: "hugegraph-commons ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        JAVA_VERSION: ['8', '11']

    steps:
      - name: Install JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: License check(RAT)
        run: |
          mvn apache-rat:check -ntp
          find ./ -name rat.txt -print0 | xargs -0 -I file cat file > merged-rat.txt
          grep "Binaries" merged-rat.txt -C 3 && cat merged-rat.txt

      - name: Compile
        run: |
          mvn compile -Dmaven.javadoc.skip=true -ntp

      - name: Run test
        run: |
          mvn test -Dtest=UnitTestSuite

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: target/jacoco.xml
