name: "license checker"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-license-header:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # More info could refer to: https://github.com/apache/skywalking-eyes
      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
          config: .licenserc.yaml

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: License check(RAT)
        run: |
          mvn apache-rat:check -ntp
          find ./ -name rat.txt -print0 | xargs -0 -I file cat file > merged-rat.txt
          grep "Binaries" merged-rat.txt -C 3 && cat merged-rat.txt

  check-dependency-license:
    runs-on: ubuntu-latest
    env:
      SCRIPT_DEPENDENCY: hugegraph-dist/scripts/dependency
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mvn install
        run: |
          mvn install -DskipTests=true -ntp
      - name: generate current dependencies
        run: |
          bash $SCRIPT_DEPENDENCY/regenerate_known_dependencies.sh current-dependencies.txt
      - name: check third dependencies
        run: |
          bash $SCRIPT_DEPENDENCY/check_dependencies.sh
