// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hugegraph-core/src/main/resources/raft.proto

package com.baidu.hugegraph.backend.store.raft;

public final class RaftRequests {
  private RaftRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.baidu.hugegraph.backend.store.raft.StoreType}
   */
  public enum StoreType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SCHEMA = 1;</code>
     */
    SCHEMA(0, 1),
    /**
     * <code>GRAPH = 2;</code>
     */
    GRAPH(1, 2),
    /**
     * <code>SYSTEM = 3;</code>
     */
    SYSTEM(2, 3),
    ;

    /**
     * <code>SCHEMA = 1;</code>
     */
    public static final int SCHEMA_VALUE = 1;
    /**
     * <code>GRAPH = 2;</code>
     */
    public static final int GRAPH_VALUE = 2;
    /**
     * <code>SYSTEM = 3;</code>
     */
    public static final int SYSTEM_VALUE = 3;


    public final int getNumber() { return value; }

    public static StoreType valueOf(int value) {
      switch (value) {
        case 1: return SCHEMA;
        case 2: return GRAPH;
        case 3: return SYSTEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StoreType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StoreType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StoreType>() {
            public StoreType findValueByNumber(int number) {
              return StoreType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.getDescriptor().getEnumTypes().get(0);
    }

    private static final StoreType[] VALUES = values();

    public static StoreType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StoreType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.baidu.hugegraph.backend.store.raft.StoreType)
  }

  /**
   * Protobuf enum {@code com.baidu.hugegraph.backend.store.raft.StoreAction}
   */
  public enum StoreAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0, 0),
    /**
     * <code>INIT = 1;</code>
     */
    INIT(1, 1),
    /**
     * <code>CLEAR = 2;</code>
     */
    CLEAR(2, 2),
    /**
     * <code>TRUNCATE = 3;</code>
     */
    TRUNCATE(3, 3),
    /**
     * <code>BEGIN_TX = 10;</code>
     */
    BEGIN_TX(4, 10),
    /**
     * <code>COMMIT_TX = 11;</code>
     */
    COMMIT_TX(5, 11),
    /**
     * <code>ROLLBACK_TX = 12;</code>
     */
    ROLLBACK_TX(6, 12),
    /**
     * <code>MUTATE = 20;</code>
     */
    MUTATE(7, 20),
    /**
     * <code>INCR_COUNTER = 21;</code>
     */
    INCR_COUNTER(8, 21),
    /**
     * <code>QUERY = 30;</code>
     */
    QUERY(9, 30),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>INIT = 1;</code>
     */
    public static final int INIT_VALUE = 1;
    /**
     * <code>CLEAR = 2;</code>
     */
    public static final int CLEAR_VALUE = 2;
    /**
     * <code>TRUNCATE = 3;</code>
     */
    public static final int TRUNCATE_VALUE = 3;
    /**
     * <code>BEGIN_TX = 10;</code>
     */
    public static final int BEGIN_TX_VALUE = 10;
    /**
     * <code>COMMIT_TX = 11;</code>
     */
    public static final int COMMIT_TX_VALUE = 11;
    /**
     * <code>ROLLBACK_TX = 12;</code>
     */
    public static final int ROLLBACK_TX_VALUE = 12;
    /**
     * <code>MUTATE = 20;</code>
     */
    public static final int MUTATE_VALUE = 20;
    /**
     * <code>INCR_COUNTER = 21;</code>
     */
    public static final int INCR_COUNTER_VALUE = 21;
    /**
     * <code>QUERY = 30;</code>
     */
    public static final int QUERY_VALUE = 30;


    public final int getNumber() { return value; }

    public static StoreAction valueOf(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return INIT;
        case 2: return CLEAR;
        case 3: return TRUNCATE;
        case 10: return BEGIN_TX;
        case 11: return COMMIT_TX;
        case 12: return ROLLBACK_TX;
        case 20: return MUTATE;
        case 21: return INCR_COUNTER;
        case 30: return QUERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StoreAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StoreAction>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StoreAction>() {
            public StoreAction findValueByNumber(int number) {
              return StoreAction.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.getDescriptor().getEnumTypes().get(1);
    }

    private static final StoreAction[] VALUES = values();

    public static StoreAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private StoreAction(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.baidu.hugegraph.backend.store.raft.StoreAction)
  }

  public interface StoreCommandRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
     */
    com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType getType();

    // required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
     */
    com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction getAction();

    // required bytes data = 3;
    /**
     * <code>required bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.baidu.hugegraph.backend.store.raft.StoreCommandRequest}
   */
  public static final class StoreCommandRequest extends
      com.google.protobuf.GeneratedMessage
      implements StoreCommandRequestOrBuilder {
    // Use StoreCommandRequest.newBuilder() to construct.
    private StoreCommandRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StoreCommandRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StoreCommandRequest defaultInstance;
    public static StoreCommandRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StoreCommandRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StoreCommandRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType value = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction value = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.class, com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StoreCommandRequest> PARSER =
        new com.google.protobuf.AbstractParser<StoreCommandRequest>() {
      public StoreCommandRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoreCommandRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StoreCommandRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType type_;
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
     */
    public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType getType() {
      return type_;
    }

    // required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction action_;
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
     */
    public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction getAction() {
      return action_;
    }

    // required bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      type_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType.SCHEMA;
      action_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction.NONE;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.hugegraph.backend.store.raft.StoreCommandRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.class, com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.Builder.class);
      }

      // Construct using com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType.SCHEMA;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction.NONE;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor;
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest getDefaultInstanceForType() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.getDefaultInstance();
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest build() {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest buildPartial() {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest result = new com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest) {
          return mergeFrom((com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest other) {
        if (other == com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasAction()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;
      private com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType type_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType.SCHEMA;
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
       */
      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType getType() {
        return type_;
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
       */
      public Builder setType(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreType.SCHEMA;
        onChanged();
        return this;
      }

      // required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;
      private com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction action_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction.NONE;
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
       */
      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction getAction() {
        return action_;
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
       */
      public Builder setAction(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.baidu.hugegraph.backend.store.raft.StoreAction action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreAction.NONE;
        onChanged();
        return this;
      }

      // required bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.hugegraph.backend.store.raft.StoreCommandRequest)
    }

    static {
      defaultInstance = new StoreCommandRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.hugegraph.backend.store.raft.StoreCommandRequest)
  }

  public interface StoreCommandResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool status = 1;
    /**
     * <code>required bool status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required bool status = 1;</code>
     */
    boolean getStatus();

    // optional string message = 2;
    /**
     * <code>optional string message = 2;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.baidu.hugegraph.backend.store.raft.StoreCommandResponse}
   */
  public static final class StoreCommandResponse extends
      com.google.protobuf.GeneratedMessage
      implements StoreCommandResponseOrBuilder {
    // Use StoreCommandResponse.newBuilder() to construct.
    private StoreCommandResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StoreCommandResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StoreCommandResponse defaultInstance;
    public static StoreCommandResponse getDefaultInstance() {
      return defaultInstance;
    }

    public StoreCommandResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StoreCommandResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.class, com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<StoreCommandResponse> PARSER =
        new com.google.protobuf.AbstractParser<StoreCommandResponse>() {
      public StoreCommandResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StoreCommandResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StoreCommandResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private boolean status_;
    /**
     * <code>required bool status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool status = 1;</code>
     */
    public boolean getStatus() {
      return status_;
    }

    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = false;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.baidu.hugegraph.backend.store.raft.StoreCommandResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.class, com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.Builder.class);
      }

      // Construct using com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor;
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse getDefaultInstanceForType() {
        return com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.getDefaultInstance();
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse build() {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse buildPartial() {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse result = new com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse) {
          return mergeFrom((com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse other) {
        if (other == com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000002;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.baidu.hugegraph.backend.store.raft.RaftRequests.StoreCommandResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool status = 1;
      private boolean status_ ;
      /**
       * <code>required bool status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool status = 1;</code>
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>required bool status = 1;</code>
       */
      public Builder setStatus(boolean value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = false;
        onChanged();
        return this;
      }

      // optional string message = 2;
      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.baidu.hugegraph.backend.store.raft.StoreCommandResponse)
    }

    static {
      defaultInstance = new StoreCommandResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.baidu.hugegraph.backend.store.raft.StoreCommandResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,hugegraph-core/src/main/resources/raft" +
      ".proto\022&com.baidu.hugegraph.backend.stor" +
      "e.raft\"\251\001\n\023StoreCommandRequest\022?\n\004type\030\001" +
      " \002(\01621.com.baidu.hugegraph.backend.store" +
      ".raft.StoreType\022C\n\006action\030\002 \002(\01623.com.ba" +
      "idu.hugegraph.backend.store.raft.StoreAc" +
      "tion\022\014\n\004data\030\003 \002(\014\"7\n\024StoreCommandRespon" +
      "se\022\016\n\006status\030\001 \002(\010\022\017\n\007message\030\002 \001(\t*.\n\tS" +
      "toreType\022\n\n\006SCHEMA\020\001\022\t\n\005GRAPH\020\002\022\n\n\006SYSTE" +
      "M\020\003*\221\001\n\013StoreAction\022\010\n\004NONE\020\000\022\010\n\004INIT\020\001\022",
      "\t\n\005CLEAR\020\002\022\014\n\010TRUNCATE\020\003\022\014\n\010BEGIN_TX\020\n\022\r" +
      "\n\tCOMMIT_TX\020\013\022\017\n\013ROLLBACK_TX\020\014\022\n\n\006MUTATE" +
      "\020\024\022\020\n\014INCR_COUNTER\020\025\022\t\n\005QUERY\020\036B6\n&com.b" +
      "aidu.hugegraph.backend.store.raftB\014RaftR" +
      "equests"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandRequest_descriptor,
              new java.lang.String[] { "Type", "Action", "Data", });
          internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_hugegraph_backend_store_raft_StoreCommandResponse_descriptor,
              new java.lang.String[] { "Status", "Message", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
